---
# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

version: "3.6"
services:
  db:
    image: "postgres"
    restart: always
    volumes:
      - ./app/backend/data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      # any request on port 5459 the physical machine will be redirected to port 5432 of the docker composer
    # networks:
    #   - backend
    environment:
      - POSTGRES_DB=wp-core
      - POSTGRES_USER=wp-usr
      - POSTGRES_PASSWORD=wp-pwd
# volumes:
#   pgdata:

# networks:
#   backend:
