import "../styles/globals.css"
import type { Metadata } from "next"
import Link from "next/link"
import { getPages } from "../utils/sanity-utils"
import Image from "next/image"
import webpunksLogoSVG from "../../../public/WEBPUNKS.svg"
import webpunksDotSVG from "../../../public/dot.svg"
import Footer from "../components/Footer/Footer"

export const metadata: Metadata = {
  title: "My Awesome WebPunks Site!",
  description: "Generated by NextJS and Sanity",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pages = await getPages()
  return (
    <html lang="en">
      <body
        className="flex flex-col w-full mx-auto min-h-screen"
        suppressHydrationWarning={true}
      >
        <div className="min-h-full">
          <div className="fixed top-0 w-full py-5 pl-20 bg-black font-bold italic text-white text-2xl">
            <Image priority src={webpunksLogoSVG} alt="Webpunks logo" />
          </div>
          <div className="w-full max-w-6xl mx-auto py-10">
            <header className="flex items-center justify-between">
              <Link
                href="/"
                className=" inline-flex pb-5 pt-20 pr-0 items-center gap-16"
              >
                Home
              </Link>
              <div className="flex items-center gap-3 text-sm text-gray-600">
                {pages.map((page) => (
                  <Link
                    key={page._id}
                    href={`/${page.slug}`}
                    className="hover:underline"
                  >
                    {page.title}
                  </Link>
                ))}
              </div>
            </header>
            <main className="">{children}</main>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  )
}
