import "../styles/globals.css"
import type { Metadata } from "next"
import { getLogoTitleBgColor, getPages } from "../utils/sanity-utils"
import Image from "next/image"
import Footer from "../components/Footer/Footer"
import Header from "../components/Header/Header"

export const metadata: Metadata = {
  title: "My Awesome WebPunks Site!",
  description: "Generated by NextJS and Sanity",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pages = await getPages()
  const logoColorTitle = await getLogoTitleBgColor()

  return (
    <html lang="en">
      <body
        className="flex flex-col w-full mx-auto min-h-screen"
        suppressHydrationWarning={true}
      >
        <div className="fixed top-0 w-full py-5 pl-20 bg-black font-bold italic text-white text-2xl">
          <Image
            priority
            src={logoColorTitle.logo}
            alt="Webpunks logo"
            width={207}
            height={27}
          />
        </div>
        <div className="min-h-full px-5">
          <div className="w-full max-w-6xl mx-auto py-10">
            <Header pages={pages} />
            <main className="">{children}</main>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  )
}
